spring:
 cloud:
   gateway:
     routes:
       - id: view-flights
         uri: lb://flights-service
         predicates:
           - Path=/flights/**
         filters:
           - AuthenticationFilter
           
       - id: restaurant-service
         uri: lb://RESTAURANT-SERVICE
         predicates:
           - Path=/restaurant/**
         filters:
           - AuthenticationFilter

       - id: user-auth
         uri: lb://node-service
         predicates:
           - Path=/auth/**
         filters:
           - StripPrefix=1
        
       - id: seats-service
         uri: lb://seats-service
         predicates:
           - Path=/seats/**
         filters:
           - StripPrefix=1
           - AuthenticationFilter

 application:
   name: API-GATEWAY


eureka:
  client:
    service-url:
      defaultZone : ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:'http://localhost:8761/eureka/'}

